<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiskiTrack.Contracts\DiskiTrack.Contracts.csproj" />
    <ProjectReference Include="..\DiskiTrack.DataAccess.Models\DiskiTrack.DataAccess.Models.csproj" />
    <ProjectReference Include="..\DiskiTrack.DataAccess.Repository\DiskiTrack.DataAccess.Repository.csproj" />
    <ProjectReference Include="..\DiskiTrack.Services\DiskiTrack.Services.csproj" />
    <ProjectReference Include="..\DiskiTrack.Services.Application\DiskiTrack.Services.Application.csproj" />
  </ItemGroup>

</Project>
